alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: super-agi-main
  num_nodes: 1
ingress:
  rules:
  - component:
      name: superagi-backend
    match:
      path:
        prefix: /api
name: superagi
region: blr
services:
- dockerfile_path: ./gui/DockerfileProd
  envs:
  - key: DB_URL
    scope: RUN_TIME
    value: ${super-agi-main.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 3000
  instance_count: 1
  name: superagi-frontend
  source_dir: ./gui
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 8001
  instance_count: 1
  name: superagi-backend
  source_dir: /