"""create vector_db_index table

Revision ID: 111f4f3af57b
Revises: d3103b0ecef1
Create Date: 2023-07-10 09:14:06.905025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111f4f3af57b'
down_revision = 'd3103b0ecef1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
