"""create knowledge table

Revision ID: 18e8e1ee3f03
Revises: 49a07c84feee
Create Date: 2023-07-10 09:13:14.067120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e8e1ee3f03'
down_revision = '49a07c84feee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
