"""Added FKs

Revision ID: 1d24469ad78e
Revises: 7a3e336c0fba
Create Date: 2023-06-30 15:41:07.212055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d24469ad78e'
down_revision = '7a3e336c0fba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agent_configurations', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'agent_execution_feeds', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'agent_execution_feeds', 'agent_executions', ['agent_execution_id'], ['id'])
    op.drop_index('ix_agent_execution_permissions_agent_execution_id', table_name='agent_execution_permissions')
    op.create_foreign_key(None, 'agent_execution_permissions', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'agent_execution_permissions', 'agent_executions', ['agent_execution_id'], ['id'])
    op.create_foreign_key(None, 'agent_executions', 'agents', ['agent_id'], ['id'])
    op.drop_index('ix_atc_agnt_template_id_key', table_name='agent_template_configs')
    op.create_foreign_key(None, 'agent_template_configs', 'agent_templates', ['agent_template_id'], ['id'])
    op.drop_index('ix_agt_agnt_name', table_name='agent_templates')
    op.drop_index('ix_agt_agnt_organisation_id', table_name='agent_templates')
    op.drop_index('ix_agt_agnt_workflow_id', table_name='agent_templates')
    op.create_foreign_key(None, 'agent_templates', 'agent_workflows', ['agent_workflow_id'], ['id'])
    op.create_foreign_key(None, 'agent_templates', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'agent_workflow_steps', 'agent_workflows', ['agent_workflow_id'], ['id'])
    op.create_foreign_key(None, 'configurations', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'resources', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'tool_configs', 'toolkits', ['toolkit_id'], ['id'])
    op.create_foreign_key(None, 'toolkits', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'tools', 'toolkits', ['toolkit_id'], ['id'])
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_constraint(None, 'toolkits', type_='foreignkey')
    op.drop_constraint(None, 'tool_configs', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'configurations', type_='foreignkey')
    op.drop_constraint(None, 'agent_workflow_steps', type_='foreignkey')
    op.drop_constraint(None, 'agent_templates', type_='foreignkey')
    op.drop_constraint(None, 'agent_templates', type_='foreignkey')
    op.create_index('ix_agt_agnt_workflow_id', 'agent_templates', ['agent_workflow_id'], unique=False)
    op.create_index('ix_agt_agnt_organisation_id', 'agent_templates', ['organisation_id'], unique=False)
    op.create_index('ix_agt_agnt_name', 'agent_templates', ['name'], unique=False)
    op.drop_constraint(None, 'agent_template_configs', type_='foreignkey')
    op.create_index('ix_atc_agnt_template_id_key', 'agent_template_configs', ['agent_template_id', 'key'], unique=False)
    op.drop_constraint(None, 'agent_executions', type_='foreignkey')
    op.drop_constraint(None, 'agent_execution_permissions', type_='foreignkey')
    op.drop_constraint(None, 'agent_execution_permissions', type_='foreignkey')
    op.create_index('ix_agent_execution_permissions_agent_execution_id', 'agent_execution_permissions', ['agent_execution_id'], unique=False)
    op.drop_constraint(None, 'agent_execution_feeds', type_='foreignkey')
    op.drop_constraint(None, 'agent_execution_feeds', type_='foreignkey')
    op.drop_constraint(None, 'agent_configurations', type_='foreignkey')
    # ### end Alembic commands ###
