"""renamed_tokens_calls

Revision ID: 2f98a4503e53
Revises: 598cfb37292a
Create Date: 2023-06-05 21:16:32.930009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f98a4503e53'
down_revision = '598cfb37292a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_template_steps',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_template_id', sa.Integer(), nullable=True),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('output_type', sa.String(), nullable=True),
    sa.Column('step_type', sa.String(), nullable=True),
    sa.Column('next_step_id', sa.Integer(), nullable=True),
    sa.Column('history_enabled', sa.Boolean(), nullable=True),
    sa.Column('completion_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_templates',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_executions', sa.Column('current_step_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('agent_template_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'agent_template_id')
    op.drop_column('agent_executions', 'current_step_id')
    op.drop_table('agent_templates')
    op.drop_table('agent_template_steps')
    # ### end Alembic commands ###
