"""create models config

Revision ID: 520aa6776347
Revises: 71e3980d55f5
Create Date: 2023-08-01 07:48:13.724938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520aa6776347'
down_revision = '71e3980d55f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_agent_schedule_agent_id', table_name='agent_schedule')
    op.drop_index('ix_agent_schedule_expiry_date', table_name='agent_schedule')
    op.drop_index('ix_agent_schedule_status', table_name='agent_schedule')
    op.drop_index('ix_events_agent_id', table_name='events')
    op.drop_index('ix_events_event_property', table_name='events')
    op.drop_index('ix_events_org_id', table_name='events')
    op.alter_column('knowledge_configs', 'knowledge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('knowledges', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vector_db_configs', 'vector_db_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vector_db_indices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vector_dbs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vector_dbs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vector_db_indices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vector_db_configs', 'vector_db_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledges', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_configs', 'knowledge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_events_org_id', 'events', ['org_id'], unique=False)
    op.create_index('ix_events_event_property', 'events', ['event_property'], unique=False)
    op.create_index('ix_events_agent_id', 'events', ['agent_id'], unique=False)
    op.create_index('ix_agent_schedule_status', 'agent_schedule', ['status'], unique=False)
    op.create_index('ix_agent_schedule_expiry_date', 'agent_schedule', ['expiry_date'], unique=False)
    op.create_index('ix_agent_schedule_agent_id', 'agent_schedule', ['agent_id'], unique=False)
    op.drop_table('models_config')
    # ### end Alembic commands ###
