"""added is_visible to agent feed

Revision ID: 5e49ed414935
Revises: 38a96ebf931a
Create Date: 2023-07-31 12:03:46.359475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e49ed414935'
down_revision = '38a96ebf931a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_execution_feeds', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_execution_feeds', 'is_visible')
    # ### end Alembic commands ###
