"""is_delete column is added in agents table

Revision ID: 61257b93d83e
Revises: 1d54db311055
Create Date: 2023-06-28 15:26:43.626146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61257b93d83e'
down_revision = '1d54db311055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_execution_permissions_agent_execution_id', table_name='agent_execution_permissions')
    op.drop_index('ix_atc_agnt_template_id_key', table_name='agent_template_configs')
    op.drop_index('ix_agt_agnt_name', table_name='agent_templates')
    op.drop_index('ix_agt_agnt_organisation_id', table_name='agent_templates')
    op.drop_index('ix_agt_agnt_workflow_id', table_name='agent_templates')
    op.add_column('agents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_deleted')
    op.create_index('ix_agt_agnt_workflow_id', 'agent_templates', ['agent_workflow_id'], unique=False)
    op.create_index('ix_agt_agnt_organisation_id', 'agent_templates', ['organisation_id'], unique=False)
    op.create_index('ix_agt_agnt_name', 'agent_templates', ['name'], unique=False)
    op.create_index('ix_atc_agnt_template_id_key', 'agent_template_configs', ['agent_template_id', 'key'], unique=False)
    op.create_index('ix_agent_execution_permissions_agent_execution_id', 'agent_execution_permissions', ['agent_execution_id'], unique=False)
    # ### end Alembic commands ###
