"""create models_readme_content table

Revision ID: 7d4a89ef9c23
Revises: f35c9b59b5a6
Create Date: 2023-09-18 08:53:41.247571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4a89ef9c23'
down_revision = '661ec8a4c32e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models_readme_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('models', sa.Column('state', sa.String(), nullable=False, server_default='INSTALLED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'state')
    op.drop_table('models_readme_content')
    # ### end Alembic commands ###
