"""renamed_tokens_calls

Revision ID: 7dd7634c8369
Revises: 2cc1179834b0
Create Date: 2023-06-05 19:07:09.152042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd7634c8369'
down_revision = '2cc1179834b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('num_of_calls', sa.Integer(), nullable=True))
    op.add_column('agent_executions', sa.Column('num_of_tokens', sa.Integer(), nullable=True))
    op.drop_column('agent_executions', 'tokens')
    op.drop_column('agent_executions', 'calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('calls', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agent_executions', sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('agent_executions', 'num_of_tokens')
    op.drop_column('agent_executions', 'num_of_calls')
    # ### end Alembic commands ###
