"""Added Columns in Agent Workflows

Revision ID: 80ea8fa19acb
Revises: 88585c347b4c
Create Date: 2023-10-06 11:46:44.881154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ea8fa19acb'
down_revision = '88585c347b4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_workflows', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.add_column('agent_workflows', sa.Column('code_yaml', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_workflows', 'code_yaml')
    op.drop_column('agent_workflows', 'organisation_id')
    # ### end Alembic commands ###
