"""Added cluster execution feed table

Revision ID: 843d7b7655c9
Revises: a97ba61bc99c
Create Date: 2023-07-27 08:41:55.694749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843d7b7655c9'
down_revision = 'a97ba61bc99c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_execution_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_execution_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('feed', sa.Text(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_execution_feeds')
    # ### end Alembic commands ###
