"""updated agent_config to agent_execution_config

Revision ID: 85aab04827fa
Revises: 0d50a089c836
Create Date: 2023-06-14 07:22:06.930663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85aab04827fa'
down_revision = '0d50a089c836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_execution_configurations', sa.Column('agent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_execution_configurations', 'agent_id')
    # ### end Alembic commands ###
