"""added_condition_workflow_step

Revision ID: 88585c347b4c
Revises: c4f2f6ba602a
Create Date: 2023-09-20 05:24:14.759428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88585c347b4c'
down_revision = 'c4f2f6ba602a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_workflow_step_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('tool_output', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_agent_schedule_agent_id', table_name='agent_schedule')
    op.drop_index('ix_agent_schedule_expiry_date', table_name='agent_schedule')
    op.drop_index('ix_agent_schedule_status', table_name='agent_schedule')
    op.alter_column('agent_workflow_steps', 'unique_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agent_workflow_steps', 'step_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agent_workflows', 'organisation_id')
    op.drop_index('ix_events_agent_id', table_name='events')
    op.drop_index('ix_events_event_property', table_name='events')
    op.drop_index('ix_events_org_id', table_name='events')
    op.alter_column('knowledge_configs', 'knowledge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('knowledges', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vector_db_configs', 'vector_db_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vector_db_indices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vector_dbs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vector_dbs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vector_db_indices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vector_db_configs', 'vector_db_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledges', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_configs', 'knowledge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_events_org_id', 'events', ['org_id'], unique=False)
    op.create_index('ix_events_event_property', 'events', ['event_property'], unique=False)
    op.create_index('ix_events_agent_id', 'events', ['agent_id'], unique=False)
    op.add_column('agent_workflows', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('agent_workflow_steps', 'step_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agent_workflow_steps', 'unique_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_agent_schedule_status', 'agent_schedule', ['status'], unique=False)
    op.create_index('ix_agent_schedule_expiry_date', 'agent_schedule', ['expiry_date'], unique=False)
    op.create_index('ix_agent_schedule_agent_id', 'agent_schedule', ['agent_id'], unique=False)
    op.drop_table('agent_workflow_step_conditions')
    # ### end Alembic commands ###
