"""modified_tools

Revision ID: a5765f0338f1
Revises: f277e86cfa3e
Create Date: 2023-06-13 04:19:40.884454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5765f0338f1'
down_revision = 'f277e86cfa3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_atc_agnt_template_id_key', table_name='agent_template_configs')
    op.drop_index('ix_agt_agnt_name', table_name='agent_templates')
    op.drop_index('ix_agt_agnt_organisation_id', table_name='agent_templates')
    op.drop_index('ix_agt_agnt_workflow_id', table_name='agent_templates')
    op.add_column('tool_kits', sa.Column('tool_code_link', sa.String(), nullable=True))
    op.add_column('tool_kits', sa.Column('tool_readme_link', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'is_deleted')
    op.drop_column('tools', 'description')
    op.drop_column('tool_kits', 'tool_readme_link')
    op.drop_column('tool_kits', 'tool_code_link')
    op.create_index('ix_agt_agnt_workflow_id', 'agent_templates', ['agent_workflow_id'], unique=False)
    op.create_index('ix_agt_agnt_organisation_id', 'agent_templates', ['organisation_id'], unique=False)
    op.create_index('ix_agt_agnt_name', 'agent_templates', ['name'], unique=False)
    op.create_index('ix_atc_agnt_template_id_key', 'agent_template_configs', ['agent_template_id', 'key'], unique=False)
    # ### end Alembic commands ###
