"""create call logs table

Revision ID: be1d922bf2ad
Revises: 2fbd6472112c
Create Date: 2023-08-08 08:42:37.148178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1d922bf2ad'
down_revision = '2fbd6472112c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_execution_name', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('tool_used', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_workflow_steps', 'unique_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agent_workflow_steps', 'step_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agent_workflows', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_workflows', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('agent_workflow_steps', 'step_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agent_workflow_steps', 'unique_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('call_logs')
    # ### end Alembic commands ###
