"""create vector_db_config table

Revision ID: d3103b0ecef1
Revises: 9d8fa6a0bd90
Create Date: 2023-07-10 09:13:48.970568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3103b0ecef1'
down_revision = '9d8fa6a0bd90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_db_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vector_db_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_db_config')
    # ### end Alembic commands ###
