"""creating events

Revision ID: e39295ec089c
Revises: 7a3e336c0fba
Create Date: 2023-06-30 12:23:12.269999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e39295ec089c'
down_revision = '83424de1347e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_value', sa.Integer(), nullable=False),
    sa.Column('json_property', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('events')
    # ### end Alembic commands ###
