"""added_Toolkit_and_ToolConfig

Revision ID: f277e86cfa3e
Revises: 8962bed0d809
Create Date: 2023-06-12 06:33:31.798333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f277e86cfa3e'
down_revision = '8962bed0d809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_kits',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('show_tool_kit', sa.Boolean(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('tool_configs', sa.Column('tool_kit_id', sa.Integer(), nullable=True))
    op.drop_column('tool_configs', 'name')
    op.drop_column('tool_configs', 'agent_id')
    op.add_column('tools', sa.Column('tool_kit_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'tool_kit_id')
    op.add_column('tool_configs', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tool_configs', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tool_configs', 'tool_kit_id')

    op.drop_table('tool_kits')
    # ### end Alembic commands ###
